name: auto_animated_example
description: Demonstrates how to use the auto_animated plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_animated:
    path: ../

flutter:
  uses-material-design: true

