version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/auto_animated"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/epub_view"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/explorer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_color"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/pdfx"
    schedule:
      interval: "weekly"
