// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package dev.flutter.pigeon;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Pigeon {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class OpenDataMessage {
    private @Nullable byte[] data;
    public @Nullable byte[] getData() { return data; }
    public void setData(@Nullable byte[] setterArg) {
      this.data = setterArg;
    }

    private @Nullable String password;
    public @Nullable String getPassword() { return password; }
    public void setPassword(@Nullable String setterArg) {
      this.password = setterArg;
    }

    public static final class Builder {
      private @Nullable byte[] data;
      public @NonNull Builder setData(@Nullable byte[] setterArg) {
        this.data = setterArg;
        return this;
      }
      private @Nullable String password;
      public @NonNull Builder setPassword(@Nullable String setterArg) {
        this.password = setterArg;
        return this;
      }
      public @NonNull OpenDataMessage build() {
        OpenDataMessage pigeonReturn = new OpenDataMessage();
        pigeonReturn.setData(data);
        pigeonReturn.setPassword(password);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(data);
      toListResult.add(password);
      return toListResult;
    }
    static @NonNull OpenDataMessage fromList(@NonNull ArrayList<Object> list) {
      OpenDataMessage pigeonResult = new OpenDataMessage();
      Object data = list.get(0);
      pigeonResult.setData((byte[])data);
      Object password = list.get(1);
      pigeonResult.setPassword((String)password);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class OpenPathMessage {
    private @Nullable String path;
    public @Nullable String getPath() { return path; }
    public void setPath(@Nullable String setterArg) {
      this.path = setterArg;
    }

    private @Nullable String password;
    public @Nullable String getPassword() { return password; }
    public void setPassword(@Nullable String setterArg) {
      this.password = setterArg;
    }

    public static final class Builder {
      private @Nullable String path;
      public @NonNull Builder setPath(@Nullable String setterArg) {
        this.path = setterArg;
        return this;
      }
      private @Nullable String password;
      public @NonNull Builder setPassword(@Nullable String setterArg) {
        this.password = setterArg;
        return this;
      }
      public @NonNull OpenPathMessage build() {
        OpenPathMessage pigeonReturn = new OpenPathMessage();
        pigeonReturn.setPath(path);
        pigeonReturn.setPassword(password);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(path);
      toListResult.add(password);
      return toListResult;
    }
    static @NonNull OpenPathMessage fromList(@NonNull ArrayList<Object> list) {
      OpenPathMessage pigeonResult = new OpenPathMessage();
      Object path = list.get(0);
      pigeonResult.setPath((String)path);
      Object password = list.get(1);
      pigeonResult.setPassword((String)password);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class OpenReply {
    private @Nullable String id;
    public @Nullable String getId() { return id; }
    public void setId(@Nullable String setterArg) {
      this.id = setterArg;
    }

    private @Nullable Long pagesCount;
    public @Nullable Long getPagesCount() { return pagesCount; }
    public void setPagesCount(@Nullable Long setterArg) {
      this.pagesCount = setterArg;
    }

    public static final class Builder {
      private @Nullable String id;
      public @NonNull Builder setId(@Nullable String setterArg) {
        this.id = setterArg;
        return this;
      }
      private @Nullable Long pagesCount;
      public @NonNull Builder setPagesCount(@Nullable Long setterArg) {
        this.pagesCount = setterArg;
        return this;
      }
      public @NonNull OpenReply build() {
        OpenReply pigeonReturn = new OpenReply();
        pigeonReturn.setId(id);
        pigeonReturn.setPagesCount(pagesCount);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(id);
      toListResult.add(pagesCount);
      return toListResult;
    }
    static @NonNull OpenReply fromList(@NonNull ArrayList<Object> list) {
      OpenReply pigeonResult = new OpenReply();
      Object id = list.get(0);
      pigeonResult.setId((String)id);
      Object pagesCount = list.get(1);
      pigeonResult.setPagesCount((pagesCount == null) ? null : ((pagesCount instanceof Integer) ? (Integer)pagesCount : (Long)pagesCount));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class IdMessage {
    private @Nullable String id;
    public @Nullable String getId() { return id; }
    public void setId(@Nullable String setterArg) {
      this.id = setterArg;
    }

    public static final class Builder {
      private @Nullable String id;
      public @NonNull Builder setId(@Nullable String setterArg) {
        this.id = setterArg;
        return this;
      }
      public @NonNull IdMessage build() {
        IdMessage pigeonReturn = new IdMessage();
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(id);
      return toListResult;
    }
    static @NonNull IdMessage fromList(@NonNull ArrayList<Object> list) {
      IdMessage pigeonResult = new IdMessage();
      Object id = list.get(0);
      pigeonResult.setId((String)id);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GetPageMessage {
    private @Nullable String documentId;
    public @Nullable String getDocumentId() { return documentId; }
    public void setDocumentId(@Nullable String setterArg) {
      this.documentId = setterArg;
    }

    private @Nullable Long pageNumber;
    public @Nullable Long getPageNumber() { return pageNumber; }
    public void setPageNumber(@Nullable Long setterArg) {
      this.pageNumber = setterArg;
    }

    private @Nullable Boolean autoCloseAndroid;
    public @Nullable Boolean getAutoCloseAndroid() { return autoCloseAndroid; }
    public void setAutoCloseAndroid(@Nullable Boolean setterArg) {
      this.autoCloseAndroid = setterArg;
    }

    public static final class Builder {
      private @Nullable String documentId;
      public @NonNull Builder setDocumentId(@Nullable String setterArg) {
        this.documentId = setterArg;
        return this;
      }
      private @Nullable Long pageNumber;
      public @NonNull Builder setPageNumber(@Nullable Long setterArg) {
        this.pageNumber = setterArg;
        return this;
      }
      private @Nullable Boolean autoCloseAndroid;
      public @NonNull Builder setAutoCloseAndroid(@Nullable Boolean setterArg) {
        this.autoCloseAndroid = setterArg;
        return this;
      }
      public @NonNull GetPageMessage build() {
        GetPageMessage pigeonReturn = new GetPageMessage();
        pigeonReturn.setDocumentId(documentId);
        pigeonReturn.setPageNumber(pageNumber);
        pigeonReturn.setAutoCloseAndroid(autoCloseAndroid);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(documentId);
      toListResult.add(pageNumber);
      toListResult.add(autoCloseAndroid);
      return toListResult;
    }
    static @NonNull GetPageMessage fromList(@NonNull ArrayList<Object> list) {
      GetPageMessage pigeonResult = new GetPageMessage();
      Object documentId = list.get(0);
      pigeonResult.setDocumentId((String)documentId);
      Object pageNumber = list.get(1);
      pigeonResult.setPageNumber((pageNumber == null) ? null : ((pageNumber instanceof Integer) ? (Integer)pageNumber : (Long)pageNumber));
      Object autoCloseAndroid = list.get(2);
      pigeonResult.setAutoCloseAndroid((Boolean)autoCloseAndroid);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GetPageReply {
    private @Nullable String id;
    public @Nullable String getId() { return id; }
    public void setId(@Nullable String setterArg) {
      this.id = setterArg;
    }

    private @Nullable Double width;
    public @Nullable Double getWidth() { return width; }
    public void setWidth(@Nullable Double setterArg) {
      this.width = setterArg;
    }

    private @Nullable Double height;
    public @Nullable Double getHeight() { return height; }
    public void setHeight(@Nullable Double setterArg) {
      this.height = setterArg;
    }

    public static final class Builder {
      private @Nullable String id;
      public @NonNull Builder setId(@Nullable String setterArg) {
        this.id = setterArg;
        return this;
      }
      private @Nullable Double width;
      public @NonNull Builder setWidth(@Nullable Double setterArg) {
        this.width = setterArg;
        return this;
      }
      private @Nullable Double height;
      public @NonNull Builder setHeight(@Nullable Double setterArg) {
        this.height = setterArg;
        return this;
      }
      public @NonNull GetPageReply build() {
        GetPageReply pigeonReturn = new GetPageReply();
        pigeonReturn.setId(id);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(id);
      toListResult.add(width);
      toListResult.add(height);
      return toListResult;
    }
    static @NonNull GetPageReply fromList(@NonNull ArrayList<Object> list) {
      GetPageReply pigeonResult = new GetPageReply();
      Object id = list.get(0);
      pigeonResult.setId((String)id);
      Object width = list.get(1);
      pigeonResult.setWidth((Double)width);
      Object height = list.get(2);
      pigeonResult.setHeight((Double)height);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RenderPageMessage {
    private @Nullable String pageId;
    public @Nullable String getPageId() { return pageId; }
    public void setPageId(@Nullable String setterArg) {
      this.pageId = setterArg;
    }

    private @Nullable Long width;
    public @Nullable Long getWidth() { return width; }
    public void setWidth(@Nullable Long setterArg) {
      this.width = setterArg;
    }

    private @Nullable Long height;
    public @Nullable Long getHeight() { return height; }
    public void setHeight(@Nullable Long setterArg) {
      this.height = setterArg;
    }

    private @Nullable Long format;
    public @Nullable Long getFormat() { return format; }
    public void setFormat(@Nullable Long setterArg) {
      this.format = setterArg;
    }

    private @Nullable String backgroundColor;
    public @Nullable String getBackgroundColor() { return backgroundColor; }
    public void setBackgroundColor(@Nullable String setterArg) {
      this.backgroundColor = setterArg;
    }

    private @Nullable Boolean crop;
    public @Nullable Boolean getCrop() { return crop; }
    public void setCrop(@Nullable Boolean setterArg) {
      this.crop = setterArg;
    }

    private @Nullable Long cropX;
    public @Nullable Long getCropX() { return cropX; }
    public void setCropX(@Nullable Long setterArg) {
      this.cropX = setterArg;
    }

    private @Nullable Long cropY;
    public @Nullable Long getCropY() { return cropY; }
    public void setCropY(@Nullable Long setterArg) {
      this.cropY = setterArg;
    }

    private @Nullable Long cropHeight;
    public @Nullable Long getCropHeight() { return cropHeight; }
    public void setCropHeight(@Nullable Long setterArg) {
      this.cropHeight = setterArg;
    }

    private @Nullable Long cropWidth;
    public @Nullable Long getCropWidth() { return cropWidth; }
    public void setCropWidth(@Nullable Long setterArg) {
      this.cropWidth = setterArg;
    }

    private @Nullable Long quality;
    public @Nullable Long getQuality() { return quality; }
    public void setQuality(@Nullable Long setterArg) {
      this.quality = setterArg;
    }

    private @Nullable Boolean forPrint;
    public @Nullable Boolean getForPrint() { return forPrint; }
    public void setForPrint(@Nullable Boolean setterArg) {
      this.forPrint = setterArg;
    }

    public static final class Builder {
      private @Nullable String pageId;
      public @NonNull Builder setPageId(@Nullable String setterArg) {
        this.pageId = setterArg;
        return this;
      }
      private @Nullable Long width;
      public @NonNull Builder setWidth(@Nullable Long setterArg) {
        this.width = setterArg;
        return this;
      }
      private @Nullable Long height;
      public @NonNull Builder setHeight(@Nullable Long setterArg) {
        this.height = setterArg;
        return this;
      }
      private @Nullable Long format;
      public @NonNull Builder setFormat(@Nullable Long setterArg) {
        this.format = setterArg;
        return this;
      }
      private @Nullable String backgroundColor;
      public @NonNull Builder setBackgroundColor(@Nullable String setterArg) {
        this.backgroundColor = setterArg;
        return this;
      }
      private @Nullable Boolean crop;
      public @NonNull Builder setCrop(@Nullable Boolean setterArg) {
        this.crop = setterArg;
        return this;
      }
      private @Nullable Long cropX;
      public @NonNull Builder setCropX(@Nullable Long setterArg) {
        this.cropX = setterArg;
        return this;
      }
      private @Nullable Long cropY;
      public @NonNull Builder setCropY(@Nullable Long setterArg) {
        this.cropY = setterArg;
        return this;
      }
      private @Nullable Long cropHeight;
      public @NonNull Builder setCropHeight(@Nullable Long setterArg) {
        this.cropHeight = setterArg;
        return this;
      }
      private @Nullable Long cropWidth;
      public @NonNull Builder setCropWidth(@Nullable Long setterArg) {
        this.cropWidth = setterArg;
        return this;
      }
      private @Nullable Long quality;
      public @NonNull Builder setQuality(@Nullable Long setterArg) {
        this.quality = setterArg;
        return this;
      }
      private @Nullable Boolean forPrint;
      public @NonNull Builder setForPrint(@Nullable Boolean setterArg) {
        this.forPrint = setterArg;
        return this;
      }
      public @NonNull RenderPageMessage build() {
        RenderPageMessage pigeonReturn = new RenderPageMessage();
        pigeonReturn.setPageId(pageId);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setFormat(format);
        pigeonReturn.setBackgroundColor(backgroundColor);
        pigeonReturn.setCrop(crop);
        pigeonReturn.setCropX(cropX);
        pigeonReturn.setCropY(cropY);
        pigeonReturn.setCropHeight(cropHeight);
        pigeonReturn.setCropWidth(cropWidth);
        pigeonReturn.setQuality(quality);
        pigeonReturn.setForPrint(forPrint);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(12);
      toListResult.add(pageId);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(format);
      toListResult.add(backgroundColor);
      toListResult.add(crop);
      toListResult.add(cropX);
      toListResult.add(cropY);
      toListResult.add(cropHeight);
      toListResult.add(cropWidth);
      toListResult.add(quality);
      toListResult.add(forPrint);
      return toListResult;
    }
    static @NonNull RenderPageMessage fromList(@NonNull ArrayList<Object> list) {
      RenderPageMessage pigeonResult = new RenderPageMessage();
      Object pageId = list.get(0);
      pigeonResult.setPageId((String)pageId);
      Object width = list.get(1);
      pigeonResult.setWidth((width == null) ? null : ((width instanceof Integer) ? (Integer)width : (Long)width));
      Object height = list.get(2);
      pigeonResult.setHeight((height == null) ? null : ((height instanceof Integer) ? (Integer)height : (Long)height));
      Object format = list.get(3);
      pigeonResult.setFormat((format == null) ? null : ((format instanceof Integer) ? (Integer)format : (Long)format));
      Object backgroundColor = list.get(4);
      pigeonResult.setBackgroundColor((String)backgroundColor);
      Object crop = list.get(5);
      pigeonResult.setCrop((Boolean)crop);
      Object cropX = list.get(6);
      pigeonResult.setCropX((cropX == null) ? null : ((cropX instanceof Integer) ? (Integer)cropX : (Long)cropX));
      Object cropY = list.get(7);
      pigeonResult.setCropY((cropY == null) ? null : ((cropY instanceof Integer) ? (Integer)cropY : (Long)cropY));
      Object cropHeight = list.get(8);
      pigeonResult.setCropHeight((cropHeight == null) ? null : ((cropHeight instanceof Integer) ? (Integer)cropHeight : (Long)cropHeight));
      Object cropWidth = list.get(9);
      pigeonResult.setCropWidth((cropWidth == null) ? null : ((cropWidth instanceof Integer) ? (Integer)cropWidth : (Long)cropWidth));
      Object quality = list.get(10);
      pigeonResult.setQuality((quality == null) ? null : ((quality instanceof Integer) ? (Integer)quality : (Long)quality));
      Object forPrint = list.get(11);
      pigeonResult.setForPrint((Boolean)forPrint);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RenderPageReply {
    private @Nullable Long width;
    public @Nullable Long getWidth() { return width; }
    public void setWidth(@Nullable Long setterArg) {
      this.width = setterArg;
    }

    private @Nullable Long height;
    public @Nullable Long getHeight() { return height; }
    public void setHeight(@Nullable Long setterArg) {
      this.height = setterArg;
    }

    private @Nullable String path;
    public @Nullable String getPath() { return path; }
    public void setPath(@Nullable String setterArg) {
      this.path = setterArg;
    }

    private @Nullable byte[] data;
    public @Nullable byte[] getData() { return data; }
    public void setData(@Nullable byte[] setterArg) {
      this.data = setterArg;
    }

    public static final class Builder {
      private @Nullable Long width;
      public @NonNull Builder setWidth(@Nullable Long setterArg) {
        this.width = setterArg;
        return this;
      }
      private @Nullable Long height;
      public @NonNull Builder setHeight(@Nullable Long setterArg) {
        this.height = setterArg;
        return this;
      }
      private @Nullable String path;
      public @NonNull Builder setPath(@Nullable String setterArg) {
        this.path = setterArg;
        return this;
      }
      private @Nullable byte[] data;
      public @NonNull Builder setData(@Nullable byte[] setterArg) {
        this.data = setterArg;
        return this;
      }
      public @NonNull RenderPageReply build() {
        RenderPageReply pigeonReturn = new RenderPageReply();
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setPath(path);
        pigeonReturn.setData(data);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(4);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(path);
      toListResult.add(data);
      return toListResult;
    }
    static @NonNull RenderPageReply fromList(@NonNull ArrayList<Object> list) {
      RenderPageReply pigeonResult = new RenderPageReply();
      Object width = list.get(0);
      pigeonResult.setWidth((width == null) ? null : ((width instanceof Integer) ? (Integer)width : (Long)width));
      Object height = list.get(1);
      pigeonResult.setHeight((height == null) ? null : ((height instanceof Integer) ? (Integer)height : (Long)height));
      Object path = list.get(2);
      pigeonResult.setPath((String)path);
      Object data = list.get(3);
      pigeonResult.setData((byte[])data);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RegisterTextureReply {
    private @Nullable Long id;
    public @Nullable Long getId() { return id; }
    public void setId(@Nullable Long setterArg) {
      this.id = setterArg;
    }

    public static final class Builder {
      private @Nullable Long id;
      public @NonNull Builder setId(@Nullable Long setterArg) {
        this.id = setterArg;
        return this;
      }
      public @NonNull RegisterTextureReply build() {
        RegisterTextureReply pigeonReturn = new RegisterTextureReply();
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(id);
      return toListResult;
    }
    static @NonNull RegisterTextureReply fromList(@NonNull ArrayList<Object> list) {
      RegisterTextureReply pigeonResult = new RegisterTextureReply();
      Object id = list.get(0);
      pigeonResult.setId((id == null) ? null : ((id instanceof Integer) ? (Integer)id : (Long)id));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class UpdateTextureMessage {
    private @Nullable String documentId;
    public @Nullable String getDocumentId() { return documentId; }
    public void setDocumentId(@Nullable String setterArg) {
      this.documentId = setterArg;
    }

    private @Nullable Long pageNumber;
    public @Nullable Long getPageNumber() { return pageNumber; }
    public void setPageNumber(@Nullable Long setterArg) {
      this.pageNumber = setterArg;
    }

    private @Nullable String pageId;
    public @Nullable String getPageId() { return pageId; }
    public void setPageId(@Nullable String setterArg) {
      this.pageId = setterArg;
    }

    private @Nullable Long textureId;
    public @Nullable Long getTextureId() { return textureId; }
    public void setTextureId(@Nullable Long setterArg) {
      this.textureId = setterArg;
    }

    private @Nullable Long width;
    public @Nullable Long getWidth() { return width; }
    public void setWidth(@Nullable Long setterArg) {
      this.width = setterArg;
    }

    private @Nullable Long height;
    public @Nullable Long getHeight() { return height; }
    public void setHeight(@Nullable Long setterArg) {
      this.height = setterArg;
    }

    private @Nullable String backgroundColor;
    public @Nullable String getBackgroundColor() { return backgroundColor; }
    public void setBackgroundColor(@Nullable String setterArg) {
      this.backgroundColor = setterArg;
    }

    private @Nullable Long sourceX;
    public @Nullable Long getSourceX() { return sourceX; }
    public void setSourceX(@Nullable Long setterArg) {
      this.sourceX = setterArg;
    }

    private @Nullable Long sourceY;
    public @Nullable Long getSourceY() { return sourceY; }
    public void setSourceY(@Nullable Long setterArg) {
      this.sourceY = setterArg;
    }

    private @Nullable Long destinationX;
    public @Nullable Long getDestinationX() { return destinationX; }
    public void setDestinationX(@Nullable Long setterArg) {
      this.destinationX = setterArg;
    }

    private @Nullable Long destinationY;
    public @Nullable Long getDestinationY() { return destinationY; }
    public void setDestinationY(@Nullable Long setterArg) {
      this.destinationY = setterArg;
    }

    private @Nullable Double fullWidth;
    public @Nullable Double getFullWidth() { return fullWidth; }
    public void setFullWidth(@Nullable Double setterArg) {
      this.fullWidth = setterArg;
    }

    private @Nullable Double fullHeight;
    public @Nullable Double getFullHeight() { return fullHeight; }
    public void setFullHeight(@Nullable Double setterArg) {
      this.fullHeight = setterArg;
    }

    private @Nullable Long textureWidth;
    public @Nullable Long getTextureWidth() { return textureWidth; }
    public void setTextureWidth(@Nullable Long setterArg) {
      this.textureWidth = setterArg;
    }

    private @Nullable Long textureHeight;
    public @Nullable Long getTextureHeight() { return textureHeight; }
    public void setTextureHeight(@Nullable Long setterArg) {
      this.textureHeight = setterArg;
    }

    private @Nullable Boolean allowAntiAliasing;
    public @Nullable Boolean getAllowAntiAliasing() { return allowAntiAliasing; }
    public void setAllowAntiAliasing(@Nullable Boolean setterArg) {
      this.allowAntiAliasing = setterArg;
    }

    public static final class Builder {
      private @Nullable String documentId;
      public @NonNull Builder setDocumentId(@Nullable String setterArg) {
        this.documentId = setterArg;
        return this;
      }
      private @Nullable Long pageNumber;
      public @NonNull Builder setPageNumber(@Nullable Long setterArg) {
        this.pageNumber = setterArg;
        return this;
      }
      private @Nullable String pageId;
      public @NonNull Builder setPageId(@Nullable String setterArg) {
        this.pageId = setterArg;
        return this;
      }
      private @Nullable Long textureId;
      public @NonNull Builder setTextureId(@Nullable Long setterArg) {
        this.textureId = setterArg;
        return this;
      }
      private @Nullable Long width;
      public @NonNull Builder setWidth(@Nullable Long setterArg) {
        this.width = setterArg;
        return this;
      }
      private @Nullable Long height;
      public @NonNull Builder setHeight(@Nullable Long setterArg) {
        this.height = setterArg;
        return this;
      }
      private @Nullable String backgroundColor;
      public @NonNull Builder setBackgroundColor(@Nullable String setterArg) {
        this.backgroundColor = setterArg;
        return this;
      }
      private @Nullable Long sourceX;
      public @NonNull Builder setSourceX(@Nullable Long setterArg) {
        this.sourceX = setterArg;
        return this;
      }
      private @Nullable Long sourceY;
      public @NonNull Builder setSourceY(@Nullable Long setterArg) {
        this.sourceY = setterArg;
        return this;
      }
      private @Nullable Long destinationX;
      public @NonNull Builder setDestinationX(@Nullable Long setterArg) {
        this.destinationX = setterArg;
        return this;
      }
      private @Nullable Long destinationY;
      public @NonNull Builder setDestinationY(@Nullable Long setterArg) {
        this.destinationY = setterArg;
        return this;
      }
      private @Nullable Double fullWidth;
      public @NonNull Builder setFullWidth(@Nullable Double setterArg) {
        this.fullWidth = setterArg;
        return this;
      }
      private @Nullable Double fullHeight;
      public @NonNull Builder setFullHeight(@Nullable Double setterArg) {
        this.fullHeight = setterArg;
        return this;
      }
      private @Nullable Long textureWidth;
      public @NonNull Builder setTextureWidth(@Nullable Long setterArg) {
        this.textureWidth = setterArg;
        return this;
      }
      private @Nullable Long textureHeight;
      public @NonNull Builder setTextureHeight(@Nullable Long setterArg) {
        this.textureHeight = setterArg;
        return this;
      }
      private @Nullable Boolean allowAntiAliasing;
      public @NonNull Builder setAllowAntiAliasing(@Nullable Boolean setterArg) {
        this.allowAntiAliasing = setterArg;
        return this;
      }
      public @NonNull UpdateTextureMessage build() {
        UpdateTextureMessage pigeonReturn = new UpdateTextureMessage();
        pigeonReturn.setDocumentId(documentId);
        pigeonReturn.setPageNumber(pageNumber);
        pigeonReturn.setPageId(pageId);
        pigeonReturn.setTextureId(textureId);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setBackgroundColor(backgroundColor);
        pigeonReturn.setSourceX(sourceX);
        pigeonReturn.setSourceY(sourceY);
        pigeonReturn.setDestinationX(destinationX);
        pigeonReturn.setDestinationY(destinationY);
        pigeonReturn.setFullWidth(fullWidth);
        pigeonReturn.setFullHeight(fullHeight);
        pigeonReturn.setTextureWidth(textureWidth);
        pigeonReturn.setTextureHeight(textureHeight);
        pigeonReturn.setAllowAntiAliasing(allowAntiAliasing);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(16);
      toListResult.add(documentId);
      toListResult.add(pageNumber);
      toListResult.add(pageId);
      toListResult.add(textureId);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(backgroundColor);
      toListResult.add(sourceX);
      toListResult.add(sourceY);
      toListResult.add(destinationX);
      toListResult.add(destinationY);
      toListResult.add(fullWidth);
      toListResult.add(fullHeight);
      toListResult.add(textureWidth);
      toListResult.add(textureHeight);
      toListResult.add(allowAntiAliasing);
      return toListResult;
    }
    static @NonNull UpdateTextureMessage fromList(@NonNull ArrayList<Object> list) {
      UpdateTextureMessage pigeonResult = new UpdateTextureMessage();
      Object documentId = list.get(0);
      pigeonResult.setDocumentId((String)documentId);
      Object pageNumber = list.get(1);
      pigeonResult.setPageNumber((pageNumber == null) ? null : ((pageNumber instanceof Integer) ? (Integer)pageNumber : (Long)pageNumber));
      Object pageId = list.get(2);
      pigeonResult.setPageId((String)pageId);
      Object textureId = list.get(3);
      pigeonResult.setTextureId((textureId == null) ? null : ((textureId instanceof Integer) ? (Integer)textureId : (Long)textureId));
      Object width = list.get(4);
      pigeonResult.setWidth((width == null) ? null : ((width instanceof Integer) ? (Integer)width : (Long)width));
      Object height = list.get(5);
      pigeonResult.setHeight((height == null) ? null : ((height instanceof Integer) ? (Integer)height : (Long)height));
      Object backgroundColor = list.get(6);
      pigeonResult.setBackgroundColor((String)backgroundColor);
      Object sourceX = list.get(7);
      pigeonResult.setSourceX((sourceX == null) ? null : ((sourceX instanceof Integer) ? (Integer)sourceX : (Long)sourceX));
      Object sourceY = list.get(8);
      pigeonResult.setSourceY((sourceY == null) ? null : ((sourceY instanceof Integer) ? (Integer)sourceY : (Long)sourceY));
      Object destinationX = list.get(9);
      pigeonResult.setDestinationX((destinationX == null) ? null : ((destinationX instanceof Integer) ? (Integer)destinationX : (Long)destinationX));
      Object destinationY = list.get(10);
      pigeonResult.setDestinationY((destinationY == null) ? null : ((destinationY instanceof Integer) ? (Integer)destinationY : (Long)destinationY));
      Object fullWidth = list.get(11);
      pigeonResult.setFullWidth((Double)fullWidth);
      Object fullHeight = list.get(12);
      pigeonResult.setFullHeight((Double)fullHeight);
      Object textureWidth = list.get(13);
      pigeonResult.setTextureWidth((textureWidth == null) ? null : ((textureWidth instanceof Integer) ? (Integer)textureWidth : (Long)textureWidth));
      Object textureHeight = list.get(14);
      pigeonResult.setTextureHeight((textureHeight == null) ? null : ((textureHeight instanceof Integer) ? (Integer)textureHeight : (Long)textureHeight));
      Object allowAntiAliasing = list.get(15);
      pigeonResult.setAllowAntiAliasing((Boolean)allowAntiAliasing);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ResizeTextureMessage {
    private @Nullable Long textureId;
    public @Nullable Long getTextureId() { return textureId; }
    public void setTextureId(@Nullable Long setterArg) {
      this.textureId = setterArg;
    }

    private @Nullable Long width;
    public @Nullable Long getWidth() { return width; }
    public void setWidth(@Nullable Long setterArg) {
      this.width = setterArg;
    }

    private @Nullable Long height;
    public @Nullable Long getHeight() { return height; }
    public void setHeight(@Nullable Long setterArg) {
      this.height = setterArg;
    }

    public static final class Builder {
      private @Nullable Long textureId;
      public @NonNull Builder setTextureId(@Nullable Long setterArg) {
        this.textureId = setterArg;
        return this;
      }
      private @Nullable Long width;
      public @NonNull Builder setWidth(@Nullable Long setterArg) {
        this.width = setterArg;
        return this;
      }
      private @Nullable Long height;
      public @NonNull Builder setHeight(@Nullable Long setterArg) {
        this.height = setterArg;
        return this;
      }
      public @NonNull ResizeTextureMessage build() {
        ResizeTextureMessage pigeonReturn = new ResizeTextureMessage();
        pigeonReturn.setTextureId(textureId);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(3);
      toListResult.add(textureId);
      toListResult.add(width);
      toListResult.add(height);
      return toListResult;
    }
    static @NonNull ResizeTextureMessage fromList(@NonNull ArrayList<Object> list) {
      ResizeTextureMessage pigeonResult = new ResizeTextureMessage();
      Object textureId = list.get(0);
      pigeonResult.setTextureId((textureId == null) ? null : ((textureId instanceof Integer) ? (Integer)textureId : (Long)textureId));
      Object width = list.get(1);
      pigeonResult.setWidth((width == null) ? null : ((width instanceof Integer) ? (Integer)width : (Long)width));
      Object height = list.get(2);
      pigeonResult.setHeight((height == null) ? null : ((height instanceof Integer) ? (Integer)height : (Long)height));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class UnregisterTextureMessage {
    private @Nullable Long id;
    public @Nullable Long getId() { return id; }
    public void setId(@Nullable Long setterArg) {
      this.id = setterArg;
    }

    public static final class Builder {
      private @Nullable Long id;
      public @NonNull Builder setId(@Nullable Long setterArg) {
        this.id = setterArg;
        return this;
      }
      public @NonNull UnregisterTextureMessage build() {
        UnregisterTextureMessage pigeonReturn = new UnregisterTextureMessage();
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(id);
      return toListResult;
    }
    static @NonNull UnregisterTextureMessage fromList(@NonNull ArrayList<Object> list) {
      UnregisterTextureMessage pigeonResult = new UnregisterTextureMessage();
      Object id = list.get(0);
      pigeonResult.setId((id == null) ? null : ((id instanceof Integer) ? (Integer)id : (Long)id));
      return pigeonResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class PdfxApiCodec extends StandardMessageCodec {
    public static final PdfxApiCodec INSTANCE = new PdfxApiCodec();
    private PdfxApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return GetPageMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)129:         
          return GetPageReply.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)130:         
          return IdMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)131:         
          return OpenDataMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)132:         
          return OpenPathMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)133:         
          return OpenReply.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)134:         
          return RegisterTextureReply.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)135:         
          return RenderPageMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)136:         
          return RenderPageReply.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)137:         
          return ResizeTextureMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)138:         
          return UnregisterTextureMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)139:         
          return UpdateTextureMessage.fromList((ArrayList<Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value)     {
      if (value instanceof GetPageMessage) {
        stream.write(128);
        writeValue(stream, ((GetPageMessage) value).toList());
      } else 
      if (value instanceof GetPageReply) {
        stream.write(129);
        writeValue(stream, ((GetPageReply) value).toList());
      } else 
      if (value instanceof IdMessage) {
        stream.write(130);
        writeValue(stream, ((IdMessage) value).toList());
      } else 
      if (value instanceof OpenDataMessage) {
        stream.write(131);
        writeValue(stream, ((OpenDataMessage) value).toList());
      } else 
      if (value instanceof OpenPathMessage) {
        stream.write(132);
        writeValue(stream, ((OpenPathMessage) value).toList());
      } else 
      if (value instanceof OpenReply) {
        stream.write(133);
        writeValue(stream, ((OpenReply) value).toList());
      } else 
      if (value instanceof RegisterTextureReply) {
        stream.write(134);
        writeValue(stream, ((RegisterTextureReply) value).toList());
      } else 
      if (value instanceof RenderPageMessage) {
        stream.write(135);
        writeValue(stream, ((RenderPageMessage) value).toList());
      } else 
      if (value instanceof RenderPageReply) {
        stream.write(136);
        writeValue(stream, ((RenderPageReply) value).toList());
      } else 
      if (value instanceof ResizeTextureMessage) {
        stream.write(137);
        writeValue(stream, ((ResizeTextureMessage) value).toList());
      } else 
      if (value instanceof UnregisterTextureMessage) {
        stream.write(138);
        writeValue(stream, ((UnregisterTextureMessage) value).toList());
      } else 
      if (value instanceof UpdateTextureMessage) {
        stream.write(139);
        writeValue(stream, ((UpdateTextureMessage) value).toList());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /**
   * Rebuild: `flutter pub run pigeon --input pigeons/message.dart`
   * After build edit ios/Classes/pigeon/messages.m
   * replace `#import <Flutter/Flutter.h>` to
   * ````
   * ````
   *
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface PdfxApi {
    void openDocumentData(@NonNull OpenDataMessage message, Result<OpenReply> result);
    void openDocumentFile(@NonNull OpenPathMessage message, Result<OpenReply> result);
    void openDocumentAsset(@NonNull OpenPathMessage message, Result<OpenReply> result);
    void closeDocument(@NonNull IdMessage message);
    void getPage(@NonNull GetPageMessage message, Result<GetPageReply> result);
    void renderPage(@NonNull RenderPageMessage message, Result<RenderPageReply> result);
    void closePage(@NonNull IdMessage message);
    @NonNull RegisterTextureReply registerTexture();
    void updateTexture(@NonNull UpdateTextureMessage message, Result<Void> result);
    void resizeTexture(@NonNull ResizeTextureMessage message, Result<Void> result);
    void unregisterTexture(@NonNull UnregisterTextureMessage message);

    /** The codec used by PdfxApi. */
    static MessageCodec<Object> getCodec() {
      return       PdfxApiCodec.INSTANCE;    }
    /**Sets up an instance of `PdfxApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, PdfxApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.openDocumentData", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              OpenDataMessage messageArg = (OpenDataMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<OpenReply> resultCallback = new Result<OpenReply>() {
                public void success(OpenReply result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.openDocumentData(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.openDocumentFile", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              OpenPathMessage messageArg = (OpenPathMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<OpenReply> resultCallback = new Result<OpenReply>() {
                public void success(OpenReply result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.openDocumentFile(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.openDocumentAsset", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              OpenPathMessage messageArg = (OpenPathMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<OpenReply> resultCallback = new Result<OpenReply>() {
                public void success(OpenReply result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.openDocumentAsset(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.closeDocument", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              IdMessage messageArg = (IdMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              api.closeDocument(messageArg);
              wrapped.add(0, null);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              wrapped = wrappedError;
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.getPage", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              GetPageMessage messageArg = (GetPageMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<GetPageReply> resultCallback = new Result<GetPageReply>() {
                public void success(GetPageReply result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.getPage(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.renderPage", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              RenderPageMessage messageArg = (RenderPageMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<RenderPageReply> resultCallback = new Result<RenderPageReply>() {
                public void success(RenderPageReply result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.renderPage(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.closePage", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              IdMessage messageArg = (IdMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              api.closePage(messageArg);
              wrapped.add(0, null);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              wrapped = wrappedError;
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.registerTexture", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              RegisterTextureReply output = api.registerTexture();
              wrapped.add(0, output);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              wrapped = wrappedError;
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.updateTexture", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              UpdateTextureMessage messageArg = (UpdateTextureMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.add(0, null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.updateTexture(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.resizeTexture", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              ResizeTextureMessage messageArg = (ResizeTextureMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.add(0, null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.resizeTexture(messageArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.PdfxApi.unregisterTexture", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              UnregisterTextureMessage messageArg = (UnregisterTextureMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              api.unregisterTexture(messageArg);
              wrapped.add(0, null);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              wrapped = wrappedError;
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  @NonNull private static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    errorList.add(exception.toString());
    errorList.add(exception.getClass().getSimpleName());
    errorList.add("Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorList;
  }
}
