name: neumorphic_example
description: Demonstrates how to use the neumorphic plugin.
version: 1.0.0+0
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  neumorphic:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/chip.png
    - assets/images/ce.png
