// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class OpenDataMessage {
  OpenDataMessage({
    this.data,
    this.password,
  });

  Uint8List? data;

  String? password;

  Object encode() {
    return <Object?>[
      data,
      password,
    ];
  }

  static OpenDataMessage decode(Object result) {
    result as List<Object?>;
    return OpenDataMessage(
      data: result[0] as Uint8List?,
      password: result[1] as String?,
    );
  }
}

class OpenPathMessage {
  OpenPathMessage({
    this.path,
    this.password,
  });

  String? path;

  String? password;

  Object encode() {
    return <Object?>[
      path,
      password,
    ];
  }

  static OpenPathMessage decode(Object result) {
    result as List<Object?>;
    return OpenPathMessage(
      path: result[0] as String?,
      password: result[1] as String?,
    );
  }
}

class OpenReply {
  OpenReply({
    this.id,
    this.pagesCount,
  });

  String? id;

  int? pagesCount;

  Object encode() {
    return <Object?>[
      id,
      pagesCount,
    ];
  }

  static OpenReply decode(Object result) {
    result as List<Object?>;
    return OpenReply(
      id: result[0] as String?,
      pagesCount: result[1] as int?,
    );
  }
}

class IdMessage {
  IdMessage({
    this.id,
  });

  String? id;

  Object encode() {
    return <Object?>[
      id,
    ];
  }

  static IdMessage decode(Object result) {
    result as List<Object?>;
    return IdMessage(
      id: result[0] as String?,
    );
  }
}

class GetPageMessage {
  GetPageMessage({
    this.documentId,
    this.pageNumber,
    this.autoCloseAndroid,
  });

  String? documentId;

  int? pageNumber;

  bool? autoCloseAndroid;

  Object encode() {
    return <Object?>[
      documentId,
      pageNumber,
      autoCloseAndroid,
    ];
  }

  static GetPageMessage decode(Object result) {
    result as List<Object?>;
    return GetPageMessage(
      documentId: result[0] as String?,
      pageNumber: result[1] as int?,
      autoCloseAndroid: result[2] as bool?,
    );
  }
}

class GetPageReply {
  GetPageReply({
    this.id,
    this.width,
    this.height,
  });

  String? id;

  double? width;

  double? height;

  Object encode() {
    return <Object?>[
      id,
      width,
      height,
    ];
  }

  static GetPageReply decode(Object result) {
    result as List<Object?>;
    return GetPageReply(
      id: result[0] as String?,
      width: result[1] as double?,
      height: result[2] as double?,
    );
  }
}

class RenderPageMessage {
  RenderPageMessage({
    this.pageId,
    this.width,
    this.height,
    this.format,
    this.backgroundColor,
    this.crop,
    this.cropX,
    this.cropY,
    this.cropHeight,
    this.cropWidth,
    this.quality,
    this.forPrint,
  });

  String? pageId;

  int? width;

  int? height;

  int? format;

  String? backgroundColor;

  bool? crop;

  int? cropX;

  int? cropY;

  int? cropHeight;

  int? cropWidth;

  int? quality;

  bool? forPrint;

  Object encode() {
    return <Object?>[
      pageId,
      width,
      height,
      format,
      backgroundColor,
      crop,
      cropX,
      cropY,
      cropHeight,
      cropWidth,
      quality,
      forPrint,
    ];
  }

  static RenderPageMessage decode(Object result) {
    result as List<Object?>;
    return RenderPageMessage(
      pageId: result[0] as String?,
      width: result[1] as int?,
      height: result[2] as int?,
      format: result[3] as int?,
      backgroundColor: result[4] as String?,
      crop: result[5] as bool?,
      cropX: result[6] as int?,
      cropY: result[7] as int?,
      cropHeight: result[8] as int?,
      cropWidth: result[9] as int?,
      quality: result[10] as int?,
      forPrint: result[11] as bool?,
    );
  }
}

class RenderPageReply {
  RenderPageReply({
    this.width,
    this.height,
    this.path,
    this.data,
  });

  int? width;

  int? height;

  String? path;

  Uint8List? data;

  Object encode() {
    return <Object?>[
      width,
      height,
      path,
      data,
    ];
  }

  static RenderPageReply decode(Object result) {
    result as List<Object?>;
    return RenderPageReply(
      width: result[0] as int?,
      height: result[1] as int?,
      path: result[2] as String?,
      data: result[3] as Uint8List?,
    );
  }
}

class RegisterTextureReply {
  RegisterTextureReply({
    this.id,
  });

  int? id;

  Object encode() {
    return <Object?>[
      id,
    ];
  }

  static RegisterTextureReply decode(Object result) {
    result as List<Object?>;
    return RegisterTextureReply(
      id: result[0] as int?,
    );
  }
}

class UpdateTextureMessage {
  UpdateTextureMessage({
    this.documentId,
    this.pageNumber,
    this.pageId,
    this.textureId,
    this.width,
    this.height,
    this.backgroundColor,
    this.sourceX,
    this.sourceY,
    this.destinationX,
    this.destinationY,
    this.fullWidth,
    this.fullHeight,
    this.textureWidth,
    this.textureHeight,
    this.allowAntiAliasing,
  });

  String? documentId;

  int? pageNumber;

  String? pageId;

  int? textureId;

  int? width;

  int? height;

  String? backgroundColor;

  int? sourceX;

  int? sourceY;

  int? destinationX;

  int? destinationY;

  double? fullWidth;

  double? fullHeight;

  int? textureWidth;

  int? textureHeight;

  bool? allowAntiAliasing;

  Object encode() {
    return <Object?>[
      documentId,
      pageNumber,
      pageId,
      textureId,
      width,
      height,
      backgroundColor,
      sourceX,
      sourceY,
      destinationX,
      destinationY,
      fullWidth,
      fullHeight,
      textureWidth,
      textureHeight,
      allowAntiAliasing,
    ];
  }

  static UpdateTextureMessage decode(Object result) {
    result as List<Object?>;
    return UpdateTextureMessage(
      documentId: result[0] as String?,
      pageNumber: result[1] as int?,
      pageId: result[2] as String?,
      textureId: result[3] as int?,
      width: result[4] as int?,
      height: result[5] as int?,
      backgroundColor: result[6] as String?,
      sourceX: result[7] as int?,
      sourceY: result[8] as int?,
      destinationX: result[9] as int?,
      destinationY: result[10] as int?,
      fullWidth: result[11] as double?,
      fullHeight: result[12] as double?,
      textureWidth: result[13] as int?,
      textureHeight: result[14] as int?,
      allowAntiAliasing: result[15] as bool?,
    );
  }
}

class ResizeTextureMessage {
  ResizeTextureMessage({
    this.textureId,
    this.width,
    this.height,
  });

  int? textureId;

  int? width;

  int? height;

  Object encode() {
    return <Object?>[
      textureId,
      width,
      height,
    ];
  }

  static ResizeTextureMessage decode(Object result) {
    result as List<Object?>;
    return ResizeTextureMessage(
      textureId: result[0] as int?,
      width: result[1] as int?,
      height: result[2] as int?,
    );
  }
}

class UnregisterTextureMessage {
  UnregisterTextureMessage({
    this.id,
  });

  int? id;

  Object encode() {
    return <Object?>[
      id,
    ];
  }

  static UnregisterTextureMessage decode(Object result) {
    result as List<Object?>;
    return UnregisterTextureMessage(
      id: result[0] as int?,
    );
  }
}

class _PdfxApiCodec extends StandardMessageCodec {
  const _PdfxApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is GetPageMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is GetPageReply) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is IdMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is OpenDataMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is OpenPathMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is OpenReply) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is RegisterTextureReply) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RenderPageMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is RenderPageReply) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ResizeTextureMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is UnregisterTextureMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is UpdateTextureMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return GetPageMessage.decode(readValue(buffer)!);
      
      case 129:       
        return GetPageReply.decode(readValue(buffer)!);
      
      case 130:       
        return IdMessage.decode(readValue(buffer)!);
      
      case 131:       
        return OpenDataMessage.decode(readValue(buffer)!);
      
      case 132:       
        return OpenPathMessage.decode(readValue(buffer)!);
      
      case 133:       
        return OpenReply.decode(readValue(buffer)!);
      
      case 134:       
        return RegisterTextureReply.decode(readValue(buffer)!);
      
      case 135:       
        return RenderPageMessage.decode(readValue(buffer)!);
      
      case 136:       
        return RenderPageReply.decode(readValue(buffer)!);
      
      case 137:       
        return ResizeTextureMessage.decode(readValue(buffer)!);
      
      case 138:       
        return UnregisterTextureMessage.decode(readValue(buffer)!);
      
      case 139:       
        return UpdateTextureMessage.decode(readValue(buffer)!);
      
      default:

        return super.readValueOfType(type, buffer);
      
    }
  }
}

/// Rebuild: `flutter pub run pigeon --input pigeons/message.dart`
/// After build edit ios/Classes/pigeon/messages.m
/// replace `#import <Flutter/Flutter.h>` to
/// ````
/// ````
///
class PdfxApi {
  /// Constructor for [PdfxApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PdfxApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _PdfxApiCodec();

  Future<OpenReply> openDocumentData(OpenDataMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.openDocumentData', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as OpenReply?)!;
    }
  }

  Future<OpenReply> openDocumentFile(OpenPathMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.openDocumentFile', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as OpenReply?)!;
    }
  }

  Future<OpenReply> openDocumentAsset(OpenPathMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.openDocumentAsset', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as OpenReply?)!;
    }
  }

  Future<void> closeDocument(IdMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.closeDocument', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<GetPageReply> getPage(GetPageMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.getPage', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as GetPageReply?)!;
    }
  }

  Future<RenderPageReply> renderPage(RenderPageMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.renderPage', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as RenderPageReply?)!;
    }
  }

  Future<void> closePage(IdMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.closePage', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<RegisterTextureReply> registerTexture() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.registerTexture', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as RegisterTextureReply?)!;
    }
  }

  Future<void> updateTexture(UpdateTextureMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.updateTexture', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resizeTexture(ResizeTextureMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.resizeTexture', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> unregisterTexture(UnregisterTextureMessage arg_message) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.PdfxApi.unregisterTexture', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_message]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}
