name: flutter_color_example
version: 1.0.0+1
description: Demonstrates how to use the flutter_color plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  flutter_color:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
