name: native_pdf_view_example
description: Demonstrates how to use the native_pdf_view plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.5.0
  path_provider: ^0.4.1
  device_info: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  native_pdf_view:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/sample.pdf
