// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[ error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null] ];
  }
  return @[ result ?: [NSNull null]  ];
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface OpenDataMessage ()
+ (OpenDataMessage *)fromList:(NSArray *)list;
+ (nullable OpenDataMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface OpenPathMessage ()
+ (OpenPathMessage *)fromList:(NSArray *)list;
+ (nullable OpenPathMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface OpenReply ()
+ (OpenReply *)fromList:(NSArray *)list;
+ (nullable OpenReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface IdMessage ()
+ (IdMessage *)fromList:(NSArray *)list;
+ (nullable IdMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface GetPageMessage ()
+ (GetPageMessage *)fromList:(NSArray *)list;
+ (nullable GetPageMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface GetPageReply ()
+ (GetPageReply *)fromList:(NSArray *)list;
+ (nullable GetPageReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface RenderPageMessage ()
+ (RenderPageMessage *)fromList:(NSArray *)list;
+ (nullable RenderPageMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface RenderPageReply ()
+ (RenderPageReply *)fromList:(NSArray *)list;
+ (nullable RenderPageReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface RegisterTextureReply ()
+ (RegisterTextureReply *)fromList:(NSArray *)list;
+ (nullable RegisterTextureReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface UpdateTextureMessage ()
+ (UpdateTextureMessage *)fromList:(NSArray *)list;
+ (nullable UpdateTextureMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface ResizeTextureMessage ()
+ (ResizeTextureMessage *)fromList:(NSArray *)list;
+ (nullable ResizeTextureMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end
@interface UnregisterTextureMessage ()
+ (UnregisterTextureMessage *)fromList:(NSArray *)list;
+ (nullable UnregisterTextureMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation OpenDataMessage
+ (instancetype)makeWithData:(nullable FlutterStandardTypedData *)data
    password:(nullable NSString *)password {
  OpenDataMessage* pigeonResult = [[OpenDataMessage alloc] init];
  pigeonResult.data = data;
  pigeonResult.password = password;
  return pigeonResult;
}
+ (OpenDataMessage *)fromList:(NSArray *)list {
  OpenDataMessage *pigeonResult = [[OpenDataMessage alloc] init];
  pigeonResult.data = GetNullableObjectAtIndex(list, 0);
  pigeonResult.password = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable OpenDataMessage *)nullableFromList:(NSArray *)list { return (list) ? [OpenDataMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.data ?: [NSNull null]),
    (self.password ?: [NSNull null]),
  ];
}
@end

@implementation OpenPathMessage
+ (instancetype)makeWithPath:(nullable NSString *)path
    password:(nullable NSString *)password {
  OpenPathMessage* pigeonResult = [[OpenPathMessage alloc] init];
  pigeonResult.path = path;
  pigeonResult.password = password;
  return pigeonResult;
}
+ (OpenPathMessage *)fromList:(NSArray *)list {
  OpenPathMessage *pigeonResult = [[OpenPathMessage alloc] init];
  pigeonResult.path = GetNullableObjectAtIndex(list, 0);
  pigeonResult.password = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable OpenPathMessage *)nullableFromList:(NSArray *)list { return (list) ? [OpenPathMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.path ?: [NSNull null]),
    (self.password ?: [NSNull null]),
  ];
}
@end

@implementation OpenReply
+ (instancetype)makeWithId:(nullable NSString *)id
    pagesCount:(nullable NSNumber *)pagesCount {
  OpenReply* pigeonResult = [[OpenReply alloc] init];
  pigeonResult.id = id;
  pigeonResult.pagesCount = pagesCount;
  return pigeonResult;
}
+ (OpenReply *)fromList:(NSArray *)list {
  OpenReply *pigeonResult = [[OpenReply alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.pagesCount = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable OpenReply *)nullableFromList:(NSArray *)list { return (list) ? [OpenReply fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.pagesCount ?: [NSNull null]),
  ];
}
@end

@implementation IdMessage
+ (instancetype)makeWithId:(nullable NSString *)id {
  IdMessage* pigeonResult = [[IdMessage alloc] init];
  pigeonResult.id = id;
  return pigeonResult;
}
+ (IdMessage *)fromList:(NSArray *)list {
  IdMessage *pigeonResult = [[IdMessage alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable IdMessage *)nullableFromList:(NSArray *)list { return (list) ? [IdMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
  ];
}
@end

@implementation GetPageMessage
+ (instancetype)makeWithDocumentId:(nullable NSString *)documentId
    pageNumber:(nullable NSNumber *)pageNumber
    autoCloseAndroid:(nullable NSNumber *)autoCloseAndroid {
  GetPageMessage* pigeonResult = [[GetPageMessage alloc] init];
  pigeonResult.documentId = documentId;
  pigeonResult.pageNumber = pageNumber;
  pigeonResult.autoCloseAndroid = autoCloseAndroid;
  return pigeonResult;
}
+ (GetPageMessage *)fromList:(NSArray *)list {
  GetPageMessage *pigeonResult = [[GetPageMessage alloc] init];
  pigeonResult.documentId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.pageNumber = GetNullableObjectAtIndex(list, 1);
  pigeonResult.autoCloseAndroid = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable GetPageMessage *)nullableFromList:(NSArray *)list { return (list) ? [GetPageMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.documentId ?: [NSNull null]),
    (self.pageNumber ?: [NSNull null]),
    (self.autoCloseAndroid ?: [NSNull null]),
  ];
}
@end

@implementation GetPageReply
+ (instancetype)makeWithId:(nullable NSString *)id
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height {
  GetPageReply* pigeonResult = [[GetPageReply alloc] init];
  pigeonResult.id = id;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (GetPageReply *)fromList:(NSArray *)list {
  GetPageReply *pigeonResult = [[GetPageReply alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.width = GetNullableObjectAtIndex(list, 1);
  pigeonResult.height = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable GetPageReply *)nullableFromList:(NSArray *)list { return (list) ? [GetPageReply fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
  ];
}
@end

@implementation RenderPageMessage
+ (instancetype)makeWithPageId:(nullable NSString *)pageId
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height
    format:(nullable NSNumber *)format
    backgroundColor:(nullable NSString *)backgroundColor
    crop:(nullable NSNumber *)crop
    cropX:(nullable NSNumber *)cropX
    cropY:(nullable NSNumber *)cropY
    cropHeight:(nullable NSNumber *)cropHeight
    cropWidth:(nullable NSNumber *)cropWidth
    quality:(nullable NSNumber *)quality
    forPrint:(nullable NSNumber *)forPrint {
  RenderPageMessage* pigeonResult = [[RenderPageMessage alloc] init];
  pigeonResult.pageId = pageId;
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.format = format;
  pigeonResult.backgroundColor = backgroundColor;
  pigeonResult.crop = crop;
  pigeonResult.cropX = cropX;
  pigeonResult.cropY = cropY;
  pigeonResult.cropHeight = cropHeight;
  pigeonResult.cropWidth = cropWidth;
  pigeonResult.quality = quality;
  pigeonResult.forPrint = forPrint;
  return pigeonResult;
}
+ (RenderPageMessage *)fromList:(NSArray *)list {
  RenderPageMessage *pigeonResult = [[RenderPageMessage alloc] init];
  pigeonResult.pageId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.width = GetNullableObjectAtIndex(list, 1);
  pigeonResult.height = GetNullableObjectAtIndex(list, 2);
  pigeonResult.format = GetNullableObjectAtIndex(list, 3);
  pigeonResult.backgroundColor = GetNullableObjectAtIndex(list, 4);
  pigeonResult.crop = GetNullableObjectAtIndex(list, 5);
  pigeonResult.cropX = GetNullableObjectAtIndex(list, 6);
  pigeonResult.cropY = GetNullableObjectAtIndex(list, 7);
  pigeonResult.cropHeight = GetNullableObjectAtIndex(list, 8);
  pigeonResult.cropWidth = GetNullableObjectAtIndex(list, 9);
  pigeonResult.quality = GetNullableObjectAtIndex(list, 10);
  pigeonResult.forPrint = GetNullableObjectAtIndex(list, 11);
  return pigeonResult;
}
+ (nullable RenderPageMessage *)nullableFromList:(NSArray *)list { return (list) ? [RenderPageMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.pageId ?: [NSNull null]),
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
    (self.format ?: [NSNull null]),
    (self.backgroundColor ?: [NSNull null]),
    (self.crop ?: [NSNull null]),
    (self.cropX ?: [NSNull null]),
    (self.cropY ?: [NSNull null]),
    (self.cropHeight ?: [NSNull null]),
    (self.cropWidth ?: [NSNull null]),
    (self.quality ?: [NSNull null]),
    (self.forPrint ?: [NSNull null]),
  ];
}
@end

@implementation RenderPageReply
+ (instancetype)makeWithWidth:(nullable NSNumber *)width
    height:(nullable NSNumber *)height
    path:(nullable NSString *)path
    data:(nullable FlutterStandardTypedData *)data {
  RenderPageReply* pigeonResult = [[RenderPageReply alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.path = path;
  pigeonResult.data = data;
  return pigeonResult;
}
+ (RenderPageReply *)fromList:(NSArray *)list {
  RenderPageReply *pigeonResult = [[RenderPageReply alloc] init];
  pigeonResult.width = GetNullableObjectAtIndex(list, 0);
  pigeonResult.height = GetNullableObjectAtIndex(list, 1);
  pigeonResult.path = GetNullableObjectAtIndex(list, 2);
  pigeonResult.data = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable RenderPageReply *)nullableFromList:(NSArray *)list { return (list) ? [RenderPageReply fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
    (self.path ?: [NSNull null]),
    (self.data ?: [NSNull null]),
  ];
}
@end

@implementation RegisterTextureReply
+ (instancetype)makeWithId:(nullable NSNumber *)id {
  RegisterTextureReply* pigeonResult = [[RegisterTextureReply alloc] init];
  pigeonResult.id = id;
  return pigeonResult;
}
+ (RegisterTextureReply *)fromList:(NSArray *)list {
  RegisterTextureReply *pigeonResult = [[RegisterTextureReply alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable RegisterTextureReply *)nullableFromList:(NSArray *)list { return (list) ? [RegisterTextureReply fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
  ];
}
@end

@implementation UpdateTextureMessage
+ (instancetype)makeWithDocumentId:(nullable NSString *)documentId
    pageNumber:(nullable NSNumber *)pageNumber
    pageId:(nullable NSString *)pageId
    textureId:(nullable NSNumber *)textureId
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height
    backgroundColor:(nullable NSString *)backgroundColor
    sourceX:(nullable NSNumber *)sourceX
    sourceY:(nullable NSNumber *)sourceY
    destinationX:(nullable NSNumber *)destinationX
    destinationY:(nullable NSNumber *)destinationY
    fullWidth:(nullable NSNumber *)fullWidth
    fullHeight:(nullable NSNumber *)fullHeight
    textureWidth:(nullable NSNumber *)textureWidth
    textureHeight:(nullable NSNumber *)textureHeight
    allowAntiAliasing:(nullable NSNumber *)allowAntiAliasing {
  UpdateTextureMessage* pigeonResult = [[UpdateTextureMessage alloc] init];
  pigeonResult.documentId = documentId;
  pigeonResult.pageNumber = pageNumber;
  pigeonResult.pageId = pageId;
  pigeonResult.textureId = textureId;
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.backgroundColor = backgroundColor;
  pigeonResult.sourceX = sourceX;
  pigeonResult.sourceY = sourceY;
  pigeonResult.destinationX = destinationX;
  pigeonResult.destinationY = destinationY;
  pigeonResult.fullWidth = fullWidth;
  pigeonResult.fullHeight = fullHeight;
  pigeonResult.textureWidth = textureWidth;
  pigeonResult.textureHeight = textureHeight;
  pigeonResult.allowAntiAliasing = allowAntiAliasing;
  return pigeonResult;
}
+ (UpdateTextureMessage *)fromList:(NSArray *)list {
  UpdateTextureMessage *pigeonResult = [[UpdateTextureMessage alloc] init];
  pigeonResult.documentId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.pageNumber = GetNullableObjectAtIndex(list, 1);
  pigeonResult.pageId = GetNullableObjectAtIndex(list, 2);
  pigeonResult.textureId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.width = GetNullableObjectAtIndex(list, 4);
  pigeonResult.height = GetNullableObjectAtIndex(list, 5);
  pigeonResult.backgroundColor = GetNullableObjectAtIndex(list, 6);
  pigeonResult.sourceX = GetNullableObjectAtIndex(list, 7);
  pigeonResult.sourceY = GetNullableObjectAtIndex(list, 8);
  pigeonResult.destinationX = GetNullableObjectAtIndex(list, 9);
  pigeonResult.destinationY = GetNullableObjectAtIndex(list, 10);
  pigeonResult.fullWidth = GetNullableObjectAtIndex(list, 11);
  pigeonResult.fullHeight = GetNullableObjectAtIndex(list, 12);
  pigeonResult.textureWidth = GetNullableObjectAtIndex(list, 13);
  pigeonResult.textureHeight = GetNullableObjectAtIndex(list, 14);
  pigeonResult.allowAntiAliasing = GetNullableObjectAtIndex(list, 15);
  return pigeonResult;
}
+ (nullable UpdateTextureMessage *)nullableFromList:(NSArray *)list { return (list) ? [UpdateTextureMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.documentId ?: [NSNull null]),
    (self.pageNumber ?: [NSNull null]),
    (self.pageId ?: [NSNull null]),
    (self.textureId ?: [NSNull null]),
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
    (self.backgroundColor ?: [NSNull null]),
    (self.sourceX ?: [NSNull null]),
    (self.sourceY ?: [NSNull null]),
    (self.destinationX ?: [NSNull null]),
    (self.destinationY ?: [NSNull null]),
    (self.fullWidth ?: [NSNull null]),
    (self.fullHeight ?: [NSNull null]),
    (self.textureWidth ?: [NSNull null]),
    (self.textureHeight ?: [NSNull null]),
    (self.allowAntiAliasing ?: [NSNull null]),
  ];
}
@end

@implementation ResizeTextureMessage
+ (instancetype)makeWithTextureId:(nullable NSNumber *)textureId
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height {
  ResizeTextureMessage* pigeonResult = [[ResizeTextureMessage alloc] init];
  pigeonResult.textureId = textureId;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (ResizeTextureMessage *)fromList:(NSArray *)list {
  ResizeTextureMessage *pigeonResult = [[ResizeTextureMessage alloc] init];
  pigeonResult.textureId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.width = GetNullableObjectAtIndex(list, 1);
  pigeonResult.height = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable ResizeTextureMessage *)nullableFromList:(NSArray *)list { return (list) ? [ResizeTextureMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.textureId ?: [NSNull null]),
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
  ];
}
@end

@implementation UnregisterTextureMessage
+ (instancetype)makeWithId:(nullable NSNumber *)id {
  UnregisterTextureMessage* pigeonResult = [[UnregisterTextureMessage alloc] init];
  pigeonResult.id = id;
  return pigeonResult;
}
+ (UnregisterTextureMessage *)fromList:(NSArray *)list {
  UnregisterTextureMessage *pigeonResult = [[UnregisterTextureMessage alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable UnregisterTextureMessage *)nullableFromList:(NSArray *)list { return (list) ? [UnregisterTextureMessage fromList:list] : nil; }
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
  ];
}
@end

@interface PdfxApiCodecReader : FlutterStandardReader
@end
@implementation PdfxApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [GetPageMessage fromList:[self readValue]];
    
    case 129:     
      return [GetPageReply fromList:[self readValue]];
    
    case 130:     
      return [IdMessage fromList:[self readValue]];
    
    case 131:     
      return [OpenDataMessage fromList:[self readValue]];
    
    case 132:     
      return [OpenPathMessage fromList:[self readValue]];
    
    case 133:     
      return [OpenReply fromList:[self readValue]];
    
    case 134:     
      return [RegisterTextureReply fromList:[self readValue]];
    
    case 135:     
      return [RenderPageMessage fromList:[self readValue]];
    
    case 136:     
      return [RenderPageReply fromList:[self readValue]];
    
    case 137:     
      return [ResizeTextureMessage fromList:[self readValue]];
    
    case 138:     
      return [UnregisterTextureMessage fromList:[self readValue]];
    
    case 139:     
      return [UpdateTextureMessage fromList:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface PdfxApiCodecWriter : FlutterStandardWriter
@end
@implementation PdfxApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[GetPageMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[GetPageReply class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[IdMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[OpenDataMessage class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[OpenPathMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[OpenReply class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[RegisterTextureReply class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[RenderPageMessage class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[RenderPageReply class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[ResizeTextureMessage class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[UnregisterTextureMessage class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else 
  if ([value isKindOfClass:[UpdateTextureMessage class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface PdfxApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PdfxApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PdfxApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PdfxApiCodecReader alloc] initWithData:data];
}
@end


NSObject<FlutterMessageCodec> *PdfxApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PdfxApiCodecReaderWriter *readerWriter = [[PdfxApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void PdfxApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PdfxApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.openDocumentData"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openDocumentDataMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(openDocumentDataMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        OpenDataMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api openDocumentDataMessage:arg_message completion:^(OpenReply *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.openDocumentFile"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openDocumentFileMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(openDocumentFileMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        OpenPathMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api openDocumentFileMessage:arg_message completion:^(OpenReply *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.openDocumentAsset"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openDocumentAssetMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(openDocumentAssetMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        OpenPathMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api openDocumentAssetMessage:arg_message completion:^(OpenReply *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.closeDocument"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(closeDocumentMessage:error:)], @"PdfxApi api (%@) doesn't respond to @selector(closeDocumentMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        IdMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api closeDocumentMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.getPage"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPageMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(getPageMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        GetPageMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api getPageMessage:arg_message completion:^(GetPageReply *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.renderPage"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(renderPageMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(renderPageMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        RenderPageMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api renderPageMessage:arg_message completion:^(RenderPageReply *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.closePage"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(closePageMessage:error:)], @"PdfxApi api (%@) doesn't respond to @selector(closePageMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        IdMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api closePageMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.registerTexture"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(registerTextureWithError:)], @"PdfxApi api (%@) doesn't respond to @selector(registerTextureWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        RegisterTextureReply *output = [api registerTextureWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.updateTexture"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updateTextureMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(updateTextureMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        UpdateTextureMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api updateTextureMessage:arg_message completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.resizeTexture"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resizeTextureMessage:completion:)], @"PdfxApi api (%@) doesn't respond to @selector(resizeTextureMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        ResizeTextureMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        [api resizeTextureMessage:arg_message completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PdfxApi.unregisterTexture"
        binaryMessenger:binaryMessenger
        codec:PdfxApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(unregisterTextureMessage:error:)], @"PdfxApi api (%@) doesn't respond to @selector(unregisterTextureMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        UnregisterTextureMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api unregisterTextureMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
